[client]
showSidebarNavigation = false
showErrorDetails = false
toolbarMode = "minimal"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
headless = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[ui]
hideTopBar = true
hideSidebarNav = true
